# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: none
schedules:
- cron: "0 20 * * *"
  displayName: "4AM (UTC +8) daily release"
  branches:
    include:
    - master

stages:
- stage: Versioning
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: versionbump
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.17.0'
      displayName: 'Install Node.js'
    - script: |
        echo "[$(date -u)] LOG: Build.SourceBranch: $(Build.SourceBranch)"
        echo "[$(date -u)] LOG: Build.SourceBranchName: $(Build.SourceBranchName)"
        echo "[$(date -u)] LOG: Build.Repository.Name: $(Build.Repository.Name)"
        echo "[$(date -u)] LOG: Build.Repository.Provider: $(Build.Repository.Provider)"
        echo "[$(date -u)] LOG: Build.Repository.Uri: $(Build.Repository.Uri)"
        echo "[$(date -u)] LOG: Build.SourceVersionMessage: $(Build.SourceVersionMessage)"
        echo "[$(date -u)] LOG: user.commitMessage: $(user.commitMessage)"

        REPO_OLDURL=$(Build.Repository.Uri)
        REPO_FIND='github'
        REPO_REPLACE='$(user.githubToken)@$REPO_FIND'
        echo "[$(date -u)] LOG: REPO_OLDURL: $REPO_OLDURL"
        echo "[$(date -u)] LOG: REPO_FIND: $REPO_FIND"
        echo "[$(date -u)] LOG: REPO_REPLACE: $REPO_REPLACE"
        REPO_URL=${REPO_OLDURL/REPO_FIND/$REPO_REPLACE}
        echo "[$(date -u)] LOG: REPO_URL: $REPO_URL"

        echo "[$(date -u)] LOG: CHECKOUT TO $(Build.SourceBranchName)"
        git checkout $(Build.SourceBranchName) -f
        echo "[$(date -u)] LOG: CONFIG NAME, EMAIL AND REMOTE"
        git config --global user.name '$(user.name)'
        git config --global user.email '$(user.email)'
        git remote add originpat 'https://$(user.githubToken)@github.com/LianwMS/autorest.az.git'
        git remote -v
      displayName: 'Checkout and Config'

    - script: |
        LAST_AUTHOR=$(git log -1 --pretty=format:'%an')
        echo "[$(date -u)] LOG: GET LAST COMMIT AUTHOR: $LAST_AUTHOR"

        if [ "$LAST_AUTHOR" = "$(user.name)" ]; then echo "Cancel pipeline as no new commit"; exit 1; fi
      displayName: 'Validation'

    - script: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "[$(date -u)] LOG: CURRENT VERSION: $CURRENT_VERSION"

        NEW_VERSION=$(npm version --git-tag-version=false patch)
        echo "[$(date -u)] LOG: NEW VERSION: $NEW_VERSION"

        echo "[$(date -u)] LOG: COMMIT AND PUSH:"
        git commit -a -m "$(user.commitMessage) $NEW_VERSION"
        git push originpat
      displayName: 'Version Bump'

    - script: |
        echo "[$(date -u)] LOG: GET LATEST TAG:"
        git describe --tags $(git rev-list --tags --max-count=1)

        echo "[$(date -u)] LOG: ADD TAG $(Build.BuildNumber)"
        git tag $(Build.BuildNumber)

        echo "[$(date -u)] LOG: GET CURRENT LATEST TAG:"
        git describe --tags $(git rev-list --tags --max-count=1)

        echo "[$(date -u)] LOG: PUSH TAG:"
        git push originpat --follow-tags
        git push originpat --tags
      displayName: 'Add Tag'

- stage: Testing
  dependsOn: Versioning
  condition: succeeded()
  jobs:
    - job: e2e

- stage: Release
  dependsOn: Testing
  condition: succeeded()
  jobs:
    - deployment: npmjs
      environment: az-npm-release
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: NodeTool@0
                inputs:
                  versionSpec: '10.17.0'
                displayName: 'Install Node.js'

              - script: |
                  # ensure latest npm is installed
                  npm install -g npm 

                  # make sure the versions are all synchronized and pull in dependencies
                  npx @microsoft/rush sync-versions
                  npx @microsoft/rush update 

                  # compile the code
                  npx @microsoft/rush rebuild 

                  # build the packages
                  npx @microsoft/rush publish --publish --pack --include-all --tag latest

                  # publish the packages (tag as preview by default)
                  echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc 
                  for file in common/temp/artifacts/packages/*.tgz 
                  do
                   common/temp/pnpm-local/node_modules/.bin/pnpm publish $file --tag latest --access public || echo no-worries 
                  done
                  rm ./.npmrc

