# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: none

stages:
- stage: Tagging
  jobs:
  - job: AddTag
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.17.0'
      displayName: 'Install Node.js'
    - script: |
        #node -p "require('./package.json').version"        
        echo "[LOG: $(date -u)] SET VARIABLE REMOTE_REPO:"
        REMOTE_REPO=https://$(user.githubtoken)@github.com/LianwMS/autorest.az.git
        
        echo "[LOG: $(date -u)] CHECK OUT MASTER BRANCH:"
        git checkout master
        
        echo "[LOG: $(date -u)] ADD TAG $(Build.BuildNumber):"
        git tag $(Build.BuildNumber)
        
        echo "[LOG: $(date -u)] GET CURRENT TAGS:"
        git tag -l
        
        echo "[LOG: $(date -u)] PUSH TAG:"
        git push $REMOTE_REPO --follow-tags        
        git push $REMOTE_REPO --tags
      displayName: 'Add Tag'
    
- stage: Testing
  dependsOn: Tagging
  condition: succeeded()
  jobs:
    - job: e2e

- stage: Release
  dependsOn: Testing
  condition: succeeded()
  jobs:
    - deployment: npmjs
      environment: az-npm-release
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: NodeTool@0
                inputs:
                  versionSpec: '10.17.0'
                displayName: 'Install Node.js'

              - script: |
                  # ensure latest npm is installed
                  npm install -g npm 

                  # make sure the versions are all synchronized and pull in dependencies
                  npx @microsoft/rush sync-versions
                  npx @microsoft/rush update 

                  # compile the code
                  npx @microsoft/rush rebuild 

                  # build the packages
                  npx @microsoft/rush publish --publish --pack --include-all --tag latest

                  # publish the packages (tag as preview by default)
                  echo "//registry.npmjs.org/:_authToken=$(azure-sdk-npm-token)" > ./.npmrc 
                  for file in common/temp/artifacts/packages/*.tgz 
                  do
                   common/temp/pnpm-local/node_modules/.bin/pnpm publish $file --tag latest --access public || echo no-worries 
                  done
                  rm ./.npmrc

